# Generated by Django 4.1.7 on 2023-03-10 10:28

from django.db import migrations, models
import django_enumfield.db.fields
import movie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', django_enumfield.db.fields.EnumField(default=8, enum=movie.models.GENRE)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('imdb', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('image', models.ImageField(null=True, upload_to=movie.models.movie_image_file_path)),
                ('actors', models.ManyToManyField(to='actor.actor')),
                ('genres', models.ManyToManyField(to='movie.genre')),
            ],
        ),
    ]
