# Generated by Django 4.1.7 on 2023-03-10 10:28

import actor.models
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('gender', django_enumfield.db.fields.EnumField(default=2, enum=actor.models.GENDER)),
                ('birth', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to=actor.models.actor_image_file_path)),
            ],
        ),
    ]
