# Generated by Django 4.1.7 on 2023-03-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth',
            field=models.DateField(),
        ),
    ]
